import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./common/components/headder";
import ProviderWrapper from "./common/ProviderWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "i2",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[linear-gradient(to_bottom_right,#fde5d2,#fee8f1,#fff9e6,#e3f2ff,#e8dfff)] min-h-screen`}
      >
        <ProviderWrapper>
          <Header />
          {children}
        </ProviderWrapper>
      </body>
    </html>
  );
}
